DXP-2044 Refactor publish/unpublish to StreamX: use StreamX CLI

diff --git a/.github/workflows/publish-to-streamx.yaml b/.github/workflows/publish-to-streamx.yaml
--- a/.github/workflows/publish-to-streamx.yaml
+++ b/.github/workflows/publish-to-streamx.yaml
@@ -19,8 +19,33 @@ jobs:
     if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204) && endsWith(github.event.client_payload.path, '.md')
     runs-on: ubuntu-latest
     steps:
-      - name: Publish to StreamX
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+
+      - name: Set up homebrew
+        uses: 'Homebrew/actions/setup-homebrew@master'
+
+      - name: Install StreamX via Homebrew
         run: |
+          brew install streamx-dev/preview-tap/streamx
+
+      - name: Publish to StreamX
+        env:
+          STREAMX_INGESTION_AUTH_TOKEN: ${{ secrets.STREAMX_TOKEN }}
+          STREAMX_INGESTION_BASE_URL: ${{ vars.STREAMX_INGESTION_BASE_URL }}
+        run: |
+          if [ -z "$STREAMX_INGESTION_AUTH_TOKEN" ]; then
+            echo "Error: STREAMX_INGESTION_AUTH_TOKEN is not set. Please configure the GitHub secret."
+            exit 1
+          fi
+          if [ -z "$STREAMX_INGESTION_BASE_URL" ]; then
+            echo "Error: STREAMX_INGESTION_BASE_URL is not set. Please configure the GitHub variables."
+            exit 1
+          fi
+
           sleep 1s
           PAGE_PATH=$(echo "${{ github.event.client_payload.path }}" | sed 's/\.md$//g')
           EDS_PAGE_URL="${{ vars.EDS_DOMAIN_URL }}$PAGE_PATH"
@@ -33,39 +58,15 @@ jobs:
             echo "Cannot fetch page from EDS. Status code is $edsResponseCode"
             exit 1
           fi
-          streamxApi=${{ vars.STREAMX_PAGE_PUBLICATION_API }}
-          streamxKey="$PAGE_PATH"
-          echo "StreamX URL: $streamxApi key: $streamxKey"
-          streamxResponseCode=$(curl -i -X POST $streamxApi \
-            --write-out %{http_code} \
-            --insecure \
-            --output streamx_response.txt \
-            -H "Authorization: Bearer ${{ secrets.STREAMX_TOKEN }}" \
-            -H "Content-Type: application/json" \
-            -d "{
-                   \"key\" : \"$streamxKey\",
-                   \"action\" : \"publish\",
-                   \"eventTime\" : null,
-                   \"properties\" : {
-                     \"sx:type\": \"page/blog\"
-                   },
-                   \"payload\" : {
-                     \"dev.streamx.blueprints.data.Page\" : {
-                       \"content\" : {
-                         \"bytes\" : $pageHtml
-                       }
-                     }
-                   }
-                }")
-          echo -e "StreamX response:\n$(cat streamx_response.txt)"
-          if [ $streamxResponseCode != 202 ]; then
-            echo "Cannot publish to StreamX. Status code is: $streamxResponseCode"
-            exit 1
+
+          RESULT=$(streamx --accept-license publish --ingestion-url=$STREAMX_INGESTION_BASE_URL pages "$PAGE_PATH" -s "content.bytes=$pageHtml" -p "sx:type=page/blog");
+          RESULT_KEY=echo "$RESULT" | grep "Sent data publication message to 'pages'" | grep -o "key \'*[^']*\'" | awk -F"\'" '{print $2}';
+          if [[ -z "$RESULT_KEY" ]]; then
+            echo "Response does not contain success status";
+            exit 1;
           fi
-          json_content=$(cat streamx_response.txt)
-          success=$(echo "$json_content" | grep -o '"success": *{[^}]*}')
-          if [[ -z "$success" ]]; then
-            echo "Response does not contain success status"
+          if [[ "$RESULT_KEY" != "$PAGE_PATH" ]]; then
+            echo "Response does not contain success status with expected key"
             exit 1
           fi
         shell: bash
