DXP-613 Add error codes

diff --git a/.github/workflows/unpublish-from-streamx.yaml b/.github/workflows/unpublish-from-streamx.yaml
--- a/.github/workflows/unpublish-from-streamx.yaml
+++ b/.github/workflows/unpublish-from-streamx.yaml
@@ -25,8 +25,14 @@ jobs:
           PAGE_PATH=$(echo "${{ github.event.client_payload.path }}" | sed 's/\.md$//g')
           streamxKey=${{ vars.STREAMX_PAGE_PUBLICATION_API }}${{ vars.STREAMX_KEY_PREFIX }}$PAGE_PATH
           echo "StreamX URL: $streamxKey"
-          streamxResponse=$(curl -i -X DELETE $streamxKey \
+          streamxResponseCode=$(curl -i -X DELETE $streamxKey \
+            --write-out %{http_code} \
+            --output streamx_response.txt \
             -H "Authorization: Bearer ${{ secrets.STREAMX_TOKEN }}")
-          echo -e "StreamX response:\n$streamxResponse"
+          echo -e "StreamX response:\n$(cat streamx_response.txt)"
+          if [ $streamxResponseCode != 202 ]; then
+            echo "Cannot unpublish from StreamX. Status code is: $streamxResponseCode"
+            exit 1
+          fi
         shell: bash
         
